config/routes.rb
ProfileWidget::Engine.routes.draw do

  resource  :profile, path: "", controller: "profile", only: [:show, :update]
  resources :surveys, only: [:create]

  namespace :admin do
    root to: "home#index"
  end

end

app/models/profile_widget/application_record.rb
module ProfileWidget
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/profile_widget/profile.rb
module ProfileWidget
  class Profile < ApplicationRecord

    has_person_name

    ##
    # Associations

    belongs_to :ownerable, polymorphic: true
    has_many   :surveys, -> { order(updated_at: :desc) }, class_name: "ProfileWidget::Survey"

  end
end

app/models/profile_widget/survey.rb
module ProfileWidget
  class Survey < ApplicationRecord

    store :answers

    belongs_to :profile_widget_profile, class_name: "ProfileWidget::Profile"

  end
end

app/controllers/profile_widget/admin/base_controller.rb
module ProfileWidget
  class Admin::BaseController < ::ApplicationController

    layout "profile_widget/application"

  end
end

app/controllers/profile_widget/admin/home_controller.rb
module ProfileWidget
  class Admin::HomeController < Admin::BaseController

    def index
      respond_to do |format|
        format.html
      end
    end

  end
end

app/controllers/profile_widget/application_controller.rb
module ProfileWidget
  class ApplicationController < ::AuthenticatedController
    protect_from_forgery with: :exception
  end
end

app/controllers/profile_widget/profile_controller.rb
module ProfileWidget
  class ProfileController < ApplicationController

    before_action :set_profile
    skip_before_action :check_onboarding

    def show
      respond_to do |format|
        format.json { render "profile" }
      end
    end

    def update
      if @profile.update(profile_params)
        @event_to_call = "profile_widget.update_success"
      else
        @event_to_call = "profile_widget.update_failure"
      end
      respond_to do |format|
        format.js
        format.json { render "profile" }
      end
    end

    private

    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :name)
    end

  end
end

app/controllers/profile_widget/surveys_controller.rb
module ProfileWidget
  class SurveysController < ApplicationController

    before_action :set_profile, :find_or_initialize_response
    skip_before_action :check_onboarding

    def create
      @survey.key = params[:survey][:key]
      @survey.responses = params[:survey][:responses]
      @survey.save
      respond_to do |format|
        format.js
      end
    end

    private

    def set_profile
      @profile = current_user.profile
    end

    def find_or_initialize_response
      @survey = ProfileWidget::Survey.find_or_create_by(key: params[:survey][:key], profile_widget_profile_id: @profile.id)
    end

  end
end

app/helpers/profile_widget/application_helper.rb
module ProfileWidget
  module ApplicationHelper
  end
end

app/views/layouts/profile_widget/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>[Widgetful] Profile Admin</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_include_tag "profile_widget/application", "data-turbolinks-track": "reload" %>
  <%= stylesheet_link_tag    "profile_widget/application", media: "all" %>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <%= link_to "Profile Widget", admin_root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <%= active_link_to "Surveys", admin_surveys_path, active: [['profile_widget/admin/surveys'], []], class: "nav-link", wrap_tag: :li, wrap_class: "nav-item" %>
    </ul>
  </div>
</nav>

<div id="wrapper">
  <div id="sidebar">
    <% if controller_name == "surveys"%>
      <ul class="list-unstyled">
        <li class="px-3 py-2">
          <%= link_to "All Surveys", admin_surveys_path, class: "d-block" %>
        </li>
        <li class="px-3 py-2">
          <%= link_to "Active", active_admin_surveys_path, class: "d-block" %>
        </li>
        <li class="px-3 py-2">
          <%= link_to "Inactive", inactive_admin_surveys_path, class: "d-block" %>
        </li>
        <li class="px-3 py-2">
          <%= link_to "Create Survey", new_admin_survey_path, class: "d-block" %>
        </li>
      </ul>
    <% end %>
  </div>
  <div id="main">
    <%= yield %>
  </div>
</div>

<script type="text/javascript">
  App.init();
</script>

</body>
</html>

app/views/profile_widget/admin/questions/_question.html.erb
<li>
  <%= question.title %>
</li>

app/views/profile_widget/admin/surveys/_form.html.erb
<%= form_with model: [:admin, @survey] do |f| %>
  <div class="form-group">
    <%= f.label :title, "Name this survey (eg. Onboarding survey)", class: "control-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <h2>Questions</h2>
  <div id="questions">
    <%= f.fields_for :questions do |question| %>
      <%= render 'question_fields', f: question %>
    <% end %>
    <div class="links mb-3">
      <%= link_to_add_association 'Add', f, :questions, class: "btn btn-secondary" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-primary", data: { disable_with: "Saving..." } %>
  </div>
<% end %>

app/views/profile_widget/admin/surveys/_question_fields.html.erb
<div class="nested-fields my-3">
  <div class="field">
    <div class="row">
      <div class="col-10">
        <div class="form-group">
          <%= f.label :title, class: "control-label d-none" %>
          <%= f.text_field :title, placeholder: "Enter your question eg. How did you hear about us?", class: "form-control" %>
        </div>
      </div>
      <div class="col-2">
        <%= link_to_remove_association f, class: "btn btn-block btn-outline-secondary" do %>
          Remove
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profile_widget/admin/surveys/edit.html.erb
<h1>Edit Survey <%= @survey.id %><br><small class="text-muted"><%= @survey.title %></small></h1>

<div class="bg-light rounded p-3">
  <%= render "form" %>
</div>

app/views/profile_widget/admin/surveys/index.html.erb
<h1>Surveys</h1>

<div class="table-repsonsive">
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
      <%= render @surveys %>
      <% if @surveys.empty? %>
        <tr>
          <td colspan="2">No surveys</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/profile_widget/admin/surveys/new.html.erb
<h1>Create Survey</h1>

<div class="bg-light rounded p-3">
  <%= render "form" %>
</div>

app/views/profile_widget/admin/surveys/show.html.erb
<h1>Survey #<%= @survey.id %><br><small class="text-muted"><%= @survey.title %></small></h1>

<%= link_to "Delete survey", admin_survey_path(@survey), method: :delete, data: { confirm_with: "Are you sure?" }, class: "text-danger" %>

<%= link_to "Edit survey", edit_admin_survey_path(@survey) %>

<div id="questions" class="mt-5">
<h2>Questions</h2>
<% if @survey.questions.empty? %>
<p>No questions added</p>
<% else %>
<ul>
  <%= render partial: "profile_widget/admin/questions/question", collection: @survey.questions, as: :question %>
</ul>
<% end %>
</div>

app/views/profile_widget/profile/update.js.erb
$(document).trigger('<%= @event_to_call %>')

app/views/profile_widget/surveys/create.js.erb
$(document).trigger('profile_widget.survey_updated')